--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/antbag-dev/PM-Vouchers
build-by-default: true
branches:
- main
projects:
  PM-Vouchers:
    path: ""
    icon: 'gift-voucher.png'
...
